# Generated by Django 5.1.1 on 2024-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
